// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Annotation.proto

#ifndef PROTOBUF_INCLUDED_Annotation_2eproto
#define PROTOBUF_INCLUDED_Annotation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/wrappers.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Annotation_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Annotation_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Annotation_2eproto();
class PAnnotation;
class PAnnotationDefaultTypeInternal;
extern PAnnotationDefaultTypeInternal _PAnnotation_default_instance_;
class PAnnotationValue;
class PAnnotationValueDefaultTypeInternal;
extern PAnnotationValueDefaultTypeInternal _PAnnotationValue_default_instance_;
class PIntBooleanIntBooleanValue;
class PIntBooleanIntBooleanValueDefaultTypeInternal;
extern PIntBooleanIntBooleanValueDefaultTypeInternal _PIntBooleanIntBooleanValue_default_instance_;
class PIntStringStringValue;
class PIntStringStringValueDefaultTypeInternal;
extern PIntStringStringValueDefaultTypeInternal _PIntStringStringValue_default_instance_;
class PIntStringValue;
class PIntStringValueDefaultTypeInternal;
extern PIntStringValueDefaultTypeInternal _PIntStringValue_default_instance_;
class PLongIntIntByteByteStringValue;
class PLongIntIntByteByteStringValueDefaultTypeInternal;
extern PLongIntIntByteByteStringValueDefaultTypeInternal _PLongIntIntByteByteStringValue_default_instance_;
class PStringStringValue;
class PStringStringValueDefaultTypeInternal;
extern PStringStringValueDefaultTypeInternal _PStringStringValue_default_instance_;
namespace google {
namespace protobuf {
template<> ::PAnnotation* Arena::CreateMaybeMessage<::PAnnotation>(Arena*);
template<> ::PAnnotationValue* Arena::CreateMaybeMessage<::PAnnotationValue>(Arena*);
template<> ::PIntBooleanIntBooleanValue* Arena::CreateMaybeMessage<::PIntBooleanIntBooleanValue>(Arena*);
template<> ::PIntStringStringValue* Arena::CreateMaybeMessage<::PIntStringStringValue>(Arena*);
template<> ::PIntStringValue* Arena::CreateMaybeMessage<::PIntStringValue>(Arena*);
template<> ::PLongIntIntByteByteStringValue* Arena::CreateMaybeMessage<::PLongIntIntByteByteStringValue>(Arena*);
template<> ::PStringStringValue* Arena::CreateMaybeMessage<::PStringStringValue>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class PIntStringValue final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PIntStringValue) */ {
 public:
  PIntStringValue();
  virtual ~PIntStringValue();

  PIntStringValue(const PIntStringValue& from);

  inline PIntStringValue& operator=(const PIntStringValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PIntStringValue(PIntStringValue&& from) noexcept
    : PIntStringValue() {
    *this = ::std::move(from);
  }

  inline PIntStringValue& operator=(PIntStringValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PIntStringValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PIntStringValue* internal_default_instance() {
    return reinterpret_cast<const PIntStringValue*>(
               &_PIntStringValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PIntStringValue* other);
  friend void swap(PIntStringValue& a, PIntStringValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PIntStringValue* New() const final {
    return CreateMaybeMessage<PIntStringValue>(nullptr);
  }

  PIntStringValue* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PIntStringValue>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PIntStringValue& from);
  void MergeFrom(const PIntStringValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PIntStringValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .google.protobuf.StringValue stringValue = 2;
  bool has_stringvalue() const;
  void clear_stringvalue();
  static const int kStringValueFieldNumber = 2;
  const ::google::protobuf::StringValue& stringvalue() const;
  ::google::protobuf::StringValue* release_stringvalue();
  ::google::protobuf::StringValue* mutable_stringvalue();
  void set_allocated_stringvalue(::google::protobuf::StringValue* stringvalue);

  // int32 intValue = 1;
  void clear_intvalue();
  static const int kIntValueFieldNumber = 1;
  ::google::protobuf::int32 intvalue() const;
  void set_intvalue(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PIntStringValue)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::StringValue* stringvalue_;
  ::google::protobuf::int32 intvalue_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Annotation_2eproto;
};
// -------------------------------------------------------------------

class PIntStringStringValue final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PIntStringStringValue) */ {
 public:
  PIntStringStringValue();
  virtual ~PIntStringStringValue();

  PIntStringStringValue(const PIntStringStringValue& from);

  inline PIntStringStringValue& operator=(const PIntStringStringValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PIntStringStringValue(PIntStringStringValue&& from) noexcept
    : PIntStringStringValue() {
    *this = ::std::move(from);
  }

  inline PIntStringStringValue& operator=(PIntStringStringValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PIntStringStringValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PIntStringStringValue* internal_default_instance() {
    return reinterpret_cast<const PIntStringStringValue*>(
               &_PIntStringStringValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(PIntStringStringValue* other);
  friend void swap(PIntStringStringValue& a, PIntStringStringValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PIntStringStringValue* New() const final {
    return CreateMaybeMessage<PIntStringStringValue>(nullptr);
  }

  PIntStringStringValue* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PIntStringStringValue>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PIntStringStringValue& from);
  void MergeFrom(const PIntStringStringValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PIntStringStringValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .google.protobuf.StringValue stringValue1 = 2;
  bool has_stringvalue1() const;
  void clear_stringvalue1();
  static const int kStringValue1FieldNumber = 2;
  const ::google::protobuf::StringValue& stringvalue1() const;
  ::google::protobuf::StringValue* release_stringvalue1();
  ::google::protobuf::StringValue* mutable_stringvalue1();
  void set_allocated_stringvalue1(::google::protobuf::StringValue* stringvalue1);

  // .google.protobuf.StringValue stringValue2 = 3;
  bool has_stringvalue2() const;
  void clear_stringvalue2();
  static const int kStringValue2FieldNumber = 3;
  const ::google::protobuf::StringValue& stringvalue2() const;
  ::google::protobuf::StringValue* release_stringvalue2();
  ::google::protobuf::StringValue* mutable_stringvalue2();
  void set_allocated_stringvalue2(::google::protobuf::StringValue* stringvalue2);

  // int32 intValue = 1;
  void clear_intvalue();
  static const int kIntValueFieldNumber = 1;
  ::google::protobuf::int32 intvalue() const;
  void set_intvalue(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PIntStringStringValue)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::StringValue* stringvalue1_;
  ::google::protobuf::StringValue* stringvalue2_;
  ::google::protobuf::int32 intvalue_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Annotation_2eproto;
};
// -------------------------------------------------------------------

class PLongIntIntByteByteStringValue final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PLongIntIntByteByteStringValue) */ {
 public:
  PLongIntIntByteByteStringValue();
  virtual ~PLongIntIntByteByteStringValue();

  PLongIntIntByteByteStringValue(const PLongIntIntByteByteStringValue& from);

  inline PLongIntIntByteByteStringValue& operator=(const PLongIntIntByteByteStringValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PLongIntIntByteByteStringValue(PLongIntIntByteByteStringValue&& from) noexcept
    : PLongIntIntByteByteStringValue() {
    *this = ::std::move(from);
  }

  inline PLongIntIntByteByteStringValue& operator=(PLongIntIntByteByteStringValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PLongIntIntByteByteStringValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PLongIntIntByteByteStringValue* internal_default_instance() {
    return reinterpret_cast<const PLongIntIntByteByteStringValue*>(
               &_PLongIntIntByteByteStringValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(PLongIntIntByteByteStringValue* other);
  friend void swap(PLongIntIntByteByteStringValue& a, PLongIntIntByteByteStringValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PLongIntIntByteByteStringValue* New() const final {
    return CreateMaybeMessage<PLongIntIntByteByteStringValue>(nullptr);
  }

  PLongIntIntByteByteStringValue* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PLongIntIntByteByteStringValue>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PLongIntIntByteByteStringValue& from);
  void MergeFrom(const PLongIntIntByteByteStringValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PLongIntIntByteByteStringValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .google.protobuf.StringValue stringValue = 6;
  bool has_stringvalue() const;
  void clear_stringvalue();
  static const int kStringValueFieldNumber = 6;
  const ::google::protobuf::StringValue& stringvalue() const;
  ::google::protobuf::StringValue* release_stringvalue();
  ::google::protobuf::StringValue* mutable_stringvalue();
  void set_allocated_stringvalue(::google::protobuf::StringValue* stringvalue);

  // int64 longValue = 1;
  void clear_longvalue();
  static const int kLongValueFieldNumber = 1;
  ::google::protobuf::int64 longvalue() const;
  void set_longvalue(::google::protobuf::int64 value);

  // int32 intValue1 = 2;
  void clear_intvalue1();
  static const int kIntValue1FieldNumber = 2;
  ::google::protobuf::int32 intvalue1() const;
  void set_intvalue1(::google::protobuf::int32 value);

  // int32 intValue2 = 3;
  void clear_intvalue2();
  static const int kIntValue2FieldNumber = 3;
  ::google::protobuf::int32 intvalue2() const;
  void set_intvalue2(::google::protobuf::int32 value);

  // sint32 byteValue1 = 4;
  void clear_bytevalue1();
  static const int kByteValue1FieldNumber = 4;
  ::google::protobuf::int32 bytevalue1() const;
  void set_bytevalue1(::google::protobuf::int32 value);

  // sint32 byteValue2 = 5;
  void clear_bytevalue2();
  static const int kByteValue2FieldNumber = 5;
  ::google::protobuf::int32 bytevalue2() const;
  void set_bytevalue2(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PLongIntIntByteByteStringValue)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::StringValue* stringvalue_;
  ::google::protobuf::int64 longvalue_;
  ::google::protobuf::int32 intvalue1_;
  ::google::protobuf::int32 intvalue2_;
  ::google::protobuf::int32 bytevalue1_;
  ::google::protobuf::int32 bytevalue2_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Annotation_2eproto;
};
// -------------------------------------------------------------------

class PIntBooleanIntBooleanValue final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PIntBooleanIntBooleanValue) */ {
 public:
  PIntBooleanIntBooleanValue();
  virtual ~PIntBooleanIntBooleanValue();

  PIntBooleanIntBooleanValue(const PIntBooleanIntBooleanValue& from);

  inline PIntBooleanIntBooleanValue& operator=(const PIntBooleanIntBooleanValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PIntBooleanIntBooleanValue(PIntBooleanIntBooleanValue&& from) noexcept
    : PIntBooleanIntBooleanValue() {
    *this = ::std::move(from);
  }

  inline PIntBooleanIntBooleanValue& operator=(PIntBooleanIntBooleanValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PIntBooleanIntBooleanValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PIntBooleanIntBooleanValue* internal_default_instance() {
    return reinterpret_cast<const PIntBooleanIntBooleanValue*>(
               &_PIntBooleanIntBooleanValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(PIntBooleanIntBooleanValue* other);
  friend void swap(PIntBooleanIntBooleanValue& a, PIntBooleanIntBooleanValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PIntBooleanIntBooleanValue* New() const final {
    return CreateMaybeMessage<PIntBooleanIntBooleanValue>(nullptr);
  }

  PIntBooleanIntBooleanValue* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PIntBooleanIntBooleanValue>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PIntBooleanIntBooleanValue& from);
  void MergeFrom(const PIntBooleanIntBooleanValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PIntBooleanIntBooleanValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 intValue1 = 1;
  void clear_intvalue1();
  static const int kIntValue1FieldNumber = 1;
  ::google::protobuf::int32 intvalue1() const;
  void set_intvalue1(::google::protobuf::int32 value);

  // int32 intValue2 = 3;
  void clear_intvalue2();
  static const int kIntValue2FieldNumber = 3;
  ::google::protobuf::int32 intvalue2() const;
  void set_intvalue2(::google::protobuf::int32 value);

  // bool boolValue1 = 2;
  void clear_boolvalue1();
  static const int kBoolValue1FieldNumber = 2;
  bool boolvalue1() const;
  void set_boolvalue1(bool value);

  // bool boolValue2 = 4;
  void clear_boolvalue2();
  static const int kBoolValue2FieldNumber = 4;
  bool boolvalue2() const;
  void set_boolvalue2(bool value);

  // @@protoc_insertion_point(class_scope:PIntBooleanIntBooleanValue)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 intvalue1_;
  ::google::protobuf::int32 intvalue2_;
  bool boolvalue1_;
  bool boolvalue2_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Annotation_2eproto;
};
// -------------------------------------------------------------------

class PStringStringValue final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PStringStringValue) */ {
 public:
  PStringStringValue();
  virtual ~PStringStringValue();

  PStringStringValue(const PStringStringValue& from);

  inline PStringStringValue& operator=(const PStringStringValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PStringStringValue(PStringStringValue&& from) noexcept
    : PStringStringValue() {
    *this = ::std::move(from);
  }

  inline PStringStringValue& operator=(PStringStringValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PStringStringValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PStringStringValue* internal_default_instance() {
    return reinterpret_cast<const PStringStringValue*>(
               &_PStringStringValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(PStringStringValue* other);
  friend void swap(PStringStringValue& a, PStringStringValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PStringStringValue* New() const final {
    return CreateMaybeMessage<PStringStringValue>(nullptr);
  }

  PStringStringValue* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PStringStringValue>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PStringStringValue& from);
  void MergeFrom(const PStringStringValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PStringStringValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .google.protobuf.StringValue stringValue1 = 1;
  bool has_stringvalue1() const;
  void clear_stringvalue1();
  static const int kStringValue1FieldNumber = 1;
  const ::google::protobuf::StringValue& stringvalue1() const;
  ::google::protobuf::StringValue* release_stringvalue1();
  ::google::protobuf::StringValue* mutable_stringvalue1();
  void set_allocated_stringvalue1(::google::protobuf::StringValue* stringvalue1);

  // .google.protobuf.StringValue stringValue2 = 2;
  bool has_stringvalue2() const;
  void clear_stringvalue2();
  static const int kStringValue2FieldNumber = 2;
  const ::google::protobuf::StringValue& stringvalue2() const;
  ::google::protobuf::StringValue* release_stringvalue2();
  ::google::protobuf::StringValue* mutable_stringvalue2();
  void set_allocated_stringvalue2(::google::protobuf::StringValue* stringvalue2);

  // @@protoc_insertion_point(class_scope:PStringStringValue)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::StringValue* stringvalue1_;
  ::google::protobuf::StringValue* stringvalue2_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Annotation_2eproto;
};
// -------------------------------------------------------------------

class PAnnotationValue final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PAnnotationValue) */ {
 public:
  PAnnotationValue();
  virtual ~PAnnotationValue();

  PAnnotationValue(const PAnnotationValue& from);

  inline PAnnotationValue& operator=(const PAnnotationValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PAnnotationValue(PAnnotationValue&& from) noexcept
    : PAnnotationValue() {
    *this = ::std::move(from);
  }

  inline PAnnotationValue& operator=(PAnnotationValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PAnnotationValue& default_instance();

  enum FieldCase {
    kStringValue = 1,
    kBoolValue = 2,
    kIntValue = 3,
    kLongValue = 4,
    kShortValue = 5,
    kDoubleValue = 6,
    kBinaryValue = 7,
    kByteValue = 8,
    kIntStringValue = 9,
    kStringStringValue = 10,
    kIntStringStringValue = 11,
    kLongIntIntByteByteStringValue = 12,
    kIntBooleanIntBooleanValue = 13,
    FIELD_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PAnnotationValue* internal_default_instance() {
    return reinterpret_cast<const PAnnotationValue*>(
               &_PAnnotationValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(PAnnotationValue* other);
  friend void swap(PAnnotationValue& a, PAnnotationValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PAnnotationValue* New() const final {
    return CreateMaybeMessage<PAnnotationValue>(nullptr);
  }

  PAnnotationValue* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PAnnotationValue>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PAnnotationValue& from);
  void MergeFrom(const PAnnotationValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PAnnotationValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string stringValue = 1;
  private:
  bool has_stringvalue() const;
  public:
  void clear_stringvalue();
  static const int kStringValueFieldNumber = 1;
  const ::std::string& stringvalue() const;
  void set_stringvalue(const ::std::string& value);
  #if LANG_CXX11
  void set_stringvalue(::std::string&& value);
  #endif
  void set_stringvalue(const char* value);
  void set_stringvalue(const char* value, size_t size);
  ::std::string* mutable_stringvalue();
  ::std::string* release_stringvalue();
  void set_allocated_stringvalue(::std::string* stringvalue);

  // bool boolValue = 2;
  private:
  bool has_boolvalue() const;
  public:
  void clear_boolvalue();
  static const int kBoolValueFieldNumber = 2;
  bool boolvalue() const;
  void set_boolvalue(bool value);

  // int32 intValue = 3;
  private:
  bool has_intvalue() const;
  public:
  void clear_intvalue();
  static const int kIntValueFieldNumber = 3;
  ::google::protobuf::int32 intvalue() const;
  void set_intvalue(::google::protobuf::int32 value);

  // int64 longValue = 4;
  private:
  bool has_longvalue() const;
  public:
  void clear_longvalue();
  static const int kLongValueFieldNumber = 4;
  ::google::protobuf::int64 longvalue() const;
  void set_longvalue(::google::protobuf::int64 value);

  // sint32 shortValue = 5;
  private:
  bool has_shortvalue() const;
  public:
  void clear_shortvalue();
  static const int kShortValueFieldNumber = 5;
  ::google::protobuf::int32 shortvalue() const;
  void set_shortvalue(::google::protobuf::int32 value);

  // double doubleValue = 6;
  private:
  bool has_doublevalue() const;
  public:
  void clear_doublevalue();
  static const int kDoubleValueFieldNumber = 6;
  double doublevalue() const;
  void set_doublevalue(double value);

  // bytes binaryValue = 7;
  private:
  bool has_binaryvalue() const;
  public:
  void clear_binaryvalue();
  static const int kBinaryValueFieldNumber = 7;
  const ::std::string& binaryvalue() const;
  void set_binaryvalue(const ::std::string& value);
  #if LANG_CXX11
  void set_binaryvalue(::std::string&& value);
  #endif
  void set_binaryvalue(const char* value);
  void set_binaryvalue(const void* value, size_t size);
  ::std::string* mutable_binaryvalue();
  ::std::string* release_binaryvalue();
  void set_allocated_binaryvalue(::std::string* binaryvalue);

  // sint32 byteValue = 8;
  private:
  bool has_bytevalue() const;
  public:
  void clear_bytevalue();
  static const int kByteValueFieldNumber = 8;
  ::google::protobuf::int32 bytevalue() const;
  void set_bytevalue(::google::protobuf::int32 value);

  // .PIntStringValue intStringValue = 9;
  bool has_intstringvalue() const;
  void clear_intstringvalue();
  static const int kIntStringValueFieldNumber = 9;
  const ::PIntStringValue& intstringvalue() const;
  ::PIntStringValue* release_intstringvalue();
  ::PIntStringValue* mutable_intstringvalue();
  void set_allocated_intstringvalue(::PIntStringValue* intstringvalue);

  // .PStringStringValue stringStringValue = 10;
  bool has_stringstringvalue() const;
  void clear_stringstringvalue();
  static const int kStringStringValueFieldNumber = 10;
  const ::PStringStringValue& stringstringvalue() const;
  ::PStringStringValue* release_stringstringvalue();
  ::PStringStringValue* mutable_stringstringvalue();
  void set_allocated_stringstringvalue(::PStringStringValue* stringstringvalue);

  // .PIntStringStringValue intStringStringValue = 11;
  bool has_intstringstringvalue() const;
  void clear_intstringstringvalue();
  static const int kIntStringStringValueFieldNumber = 11;
  const ::PIntStringStringValue& intstringstringvalue() const;
  ::PIntStringStringValue* release_intstringstringvalue();
  ::PIntStringStringValue* mutable_intstringstringvalue();
  void set_allocated_intstringstringvalue(::PIntStringStringValue* intstringstringvalue);

  // .PLongIntIntByteByteStringValue longIntIntByteByteStringValue = 12;
  bool has_longintintbytebytestringvalue() const;
  void clear_longintintbytebytestringvalue();
  static const int kLongIntIntByteByteStringValueFieldNumber = 12;
  const ::PLongIntIntByteByteStringValue& longintintbytebytestringvalue() const;
  ::PLongIntIntByteByteStringValue* release_longintintbytebytestringvalue();
  ::PLongIntIntByteByteStringValue* mutable_longintintbytebytestringvalue();
  void set_allocated_longintintbytebytestringvalue(::PLongIntIntByteByteStringValue* longintintbytebytestringvalue);

  // .PIntBooleanIntBooleanValue intBooleanIntBooleanValue = 13;
  bool has_intbooleanintbooleanvalue() const;
  void clear_intbooleanintbooleanvalue();
  static const int kIntBooleanIntBooleanValueFieldNumber = 13;
  const ::PIntBooleanIntBooleanValue& intbooleanintbooleanvalue() const;
  ::PIntBooleanIntBooleanValue* release_intbooleanintbooleanvalue();
  ::PIntBooleanIntBooleanValue* mutable_intbooleanintbooleanvalue();
  void set_allocated_intbooleanintbooleanvalue(::PIntBooleanIntBooleanValue* intbooleanintbooleanvalue);

  void clear_field();
  FieldCase field_case() const;
  // @@protoc_insertion_point(class_scope:PAnnotationValue)
 private:
  class HasBitSetters;
  void set_has_stringvalue();
  void set_has_boolvalue();
  void set_has_intvalue();
  void set_has_longvalue();
  void set_has_shortvalue();
  void set_has_doublevalue();
  void set_has_binaryvalue();
  void set_has_bytevalue();
  void set_has_intstringvalue();
  void set_has_stringstringvalue();
  void set_has_intstringstringvalue();
  void set_has_longintintbytebytestringvalue();
  void set_has_intbooleanintbooleanvalue();

  inline bool has_field() const;
  inline void clear_has_field();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  union FieldUnion {
    FieldUnion() {}
    ::google::protobuf::internal::ArenaStringPtr stringvalue_;
    bool boolvalue_;
    ::google::protobuf::int32 intvalue_;
    ::google::protobuf::int64 longvalue_;
    ::google::protobuf::int32 shortvalue_;
    double doublevalue_;
    ::google::protobuf::internal::ArenaStringPtr binaryvalue_;
    ::google::protobuf::int32 bytevalue_;
    ::PIntStringValue* intstringvalue_;
    ::PStringStringValue* stringstringvalue_;
    ::PIntStringStringValue* intstringstringvalue_;
    ::PLongIntIntByteByteStringValue* longintintbytebytestringvalue_;
    ::PIntBooleanIntBooleanValue* intbooleanintbooleanvalue_;
  } field_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::TableStruct_Annotation_2eproto;
};
// -------------------------------------------------------------------

class PAnnotation final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PAnnotation) */ {
 public:
  PAnnotation();
  virtual ~PAnnotation();

  PAnnotation(const PAnnotation& from);

  inline PAnnotation& operator=(const PAnnotation& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PAnnotation(PAnnotation&& from) noexcept
    : PAnnotation() {
    *this = ::std::move(from);
  }

  inline PAnnotation& operator=(PAnnotation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PAnnotation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PAnnotation* internal_default_instance() {
    return reinterpret_cast<const PAnnotation*>(
               &_PAnnotation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(PAnnotation* other);
  friend void swap(PAnnotation& a, PAnnotation& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PAnnotation* New() const final {
    return CreateMaybeMessage<PAnnotation>(nullptr);
  }

  PAnnotation* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PAnnotation>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PAnnotation& from);
  void MergeFrom(const PAnnotation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PAnnotation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .PAnnotationValue value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::PAnnotationValue& value() const;
  ::PAnnotationValue* release_value();
  ::PAnnotationValue* mutable_value();
  void set_allocated_value(::PAnnotationValue* value);

  // int32 key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::int32 key() const;
  void set_key(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PAnnotation)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::PAnnotationValue* value_;
  ::google::protobuf::int32 key_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Annotation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PIntStringValue

// int32 intValue = 1;
inline void PIntStringValue::clear_intvalue() {
  intvalue_ = 0;
}
inline ::google::protobuf::int32 PIntStringValue::intvalue() const {
  // @@protoc_insertion_point(field_get:PIntStringValue.intValue)
  return intvalue_;
}
inline void PIntStringValue::set_intvalue(::google::protobuf::int32 value) {
  
  intvalue_ = value;
  // @@protoc_insertion_point(field_set:PIntStringValue.intValue)
}

// .google.protobuf.StringValue stringValue = 2;
inline bool PIntStringValue::has_stringvalue() const {
  return this != internal_default_instance() && stringvalue_ != nullptr;
}
inline const ::google::protobuf::StringValue& PIntStringValue::stringvalue() const {
  const ::google::protobuf::StringValue* p = stringvalue_;
  // @@protoc_insertion_point(field_get:PIntStringValue.stringValue)
  return p != nullptr ? *p : *reinterpret_cast<const ::google::protobuf::StringValue*>(
      &::google::protobuf::_StringValue_default_instance_);
}
inline ::google::protobuf::StringValue* PIntStringValue::release_stringvalue() {
  // @@protoc_insertion_point(field_release:PIntStringValue.stringValue)
  
  ::google::protobuf::StringValue* temp = stringvalue_;
  stringvalue_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PIntStringValue::mutable_stringvalue() {
  
  if (stringvalue_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::StringValue>(GetArenaNoVirtual());
    stringvalue_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PIntStringValue.stringValue)
  return stringvalue_;
}
inline void PIntStringValue::set_allocated_stringvalue(::google::protobuf::StringValue* stringvalue) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(stringvalue_);
  }
  if (stringvalue) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(stringvalue)->GetArena();
    if (message_arena != submessage_arena) {
      stringvalue = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, stringvalue, submessage_arena);
    }
    
  } else {
    
  }
  stringvalue_ = stringvalue;
  // @@protoc_insertion_point(field_set_allocated:PIntStringValue.stringValue)
}

// -------------------------------------------------------------------

// PIntStringStringValue

// int32 intValue = 1;
inline void PIntStringStringValue::clear_intvalue() {
  intvalue_ = 0;
}
inline ::google::protobuf::int32 PIntStringStringValue::intvalue() const {
  // @@protoc_insertion_point(field_get:PIntStringStringValue.intValue)
  return intvalue_;
}
inline void PIntStringStringValue::set_intvalue(::google::protobuf::int32 value) {
  
  intvalue_ = value;
  // @@protoc_insertion_point(field_set:PIntStringStringValue.intValue)
}

// .google.protobuf.StringValue stringValue1 = 2;
inline bool PIntStringStringValue::has_stringvalue1() const {
  return this != internal_default_instance() && stringvalue1_ != nullptr;
}
inline const ::google::protobuf::StringValue& PIntStringStringValue::stringvalue1() const {
  const ::google::protobuf::StringValue* p = stringvalue1_;
  // @@protoc_insertion_point(field_get:PIntStringStringValue.stringValue1)
  return p != nullptr ? *p : *reinterpret_cast<const ::google::protobuf::StringValue*>(
      &::google::protobuf::_StringValue_default_instance_);
}
inline ::google::protobuf::StringValue* PIntStringStringValue::release_stringvalue1() {
  // @@protoc_insertion_point(field_release:PIntStringStringValue.stringValue1)
  
  ::google::protobuf::StringValue* temp = stringvalue1_;
  stringvalue1_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PIntStringStringValue::mutable_stringvalue1() {
  
  if (stringvalue1_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::StringValue>(GetArenaNoVirtual());
    stringvalue1_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PIntStringStringValue.stringValue1)
  return stringvalue1_;
}
inline void PIntStringStringValue::set_allocated_stringvalue1(::google::protobuf::StringValue* stringvalue1) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(stringvalue1_);
  }
  if (stringvalue1) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(stringvalue1)->GetArena();
    if (message_arena != submessage_arena) {
      stringvalue1 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, stringvalue1, submessage_arena);
    }
    
  } else {
    
  }
  stringvalue1_ = stringvalue1;
  // @@protoc_insertion_point(field_set_allocated:PIntStringStringValue.stringValue1)
}

// .google.protobuf.StringValue stringValue2 = 3;
inline bool PIntStringStringValue::has_stringvalue2() const {
  return this != internal_default_instance() && stringvalue2_ != nullptr;
}
inline const ::google::protobuf::StringValue& PIntStringStringValue::stringvalue2() const {
  const ::google::protobuf::StringValue* p = stringvalue2_;
  // @@protoc_insertion_point(field_get:PIntStringStringValue.stringValue2)
  return p != nullptr ? *p : *reinterpret_cast<const ::google::protobuf::StringValue*>(
      &::google::protobuf::_StringValue_default_instance_);
}
inline ::google::protobuf::StringValue* PIntStringStringValue::release_stringvalue2() {
  // @@protoc_insertion_point(field_release:PIntStringStringValue.stringValue2)
  
  ::google::protobuf::StringValue* temp = stringvalue2_;
  stringvalue2_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PIntStringStringValue::mutable_stringvalue2() {
  
  if (stringvalue2_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::StringValue>(GetArenaNoVirtual());
    stringvalue2_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PIntStringStringValue.stringValue2)
  return stringvalue2_;
}
inline void PIntStringStringValue::set_allocated_stringvalue2(::google::protobuf::StringValue* stringvalue2) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(stringvalue2_);
  }
  if (stringvalue2) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(stringvalue2)->GetArena();
    if (message_arena != submessage_arena) {
      stringvalue2 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, stringvalue2, submessage_arena);
    }
    
  } else {
    
  }
  stringvalue2_ = stringvalue2;
  // @@protoc_insertion_point(field_set_allocated:PIntStringStringValue.stringValue2)
}

// -------------------------------------------------------------------

// PLongIntIntByteByteStringValue

// int64 longValue = 1;
inline void PLongIntIntByteByteStringValue::clear_longvalue() {
  longvalue_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 PLongIntIntByteByteStringValue::longvalue() const {
  // @@protoc_insertion_point(field_get:PLongIntIntByteByteStringValue.longValue)
  return longvalue_;
}
inline void PLongIntIntByteByteStringValue::set_longvalue(::google::protobuf::int64 value) {
  
  longvalue_ = value;
  // @@protoc_insertion_point(field_set:PLongIntIntByteByteStringValue.longValue)
}

// int32 intValue1 = 2;
inline void PLongIntIntByteByteStringValue::clear_intvalue1() {
  intvalue1_ = 0;
}
inline ::google::protobuf::int32 PLongIntIntByteByteStringValue::intvalue1() const {
  // @@protoc_insertion_point(field_get:PLongIntIntByteByteStringValue.intValue1)
  return intvalue1_;
}
inline void PLongIntIntByteByteStringValue::set_intvalue1(::google::protobuf::int32 value) {
  
  intvalue1_ = value;
  // @@protoc_insertion_point(field_set:PLongIntIntByteByteStringValue.intValue1)
}

// int32 intValue2 = 3;
inline void PLongIntIntByteByteStringValue::clear_intvalue2() {
  intvalue2_ = 0;
}
inline ::google::protobuf::int32 PLongIntIntByteByteStringValue::intvalue2() const {
  // @@protoc_insertion_point(field_get:PLongIntIntByteByteStringValue.intValue2)
  return intvalue2_;
}
inline void PLongIntIntByteByteStringValue::set_intvalue2(::google::protobuf::int32 value) {
  
  intvalue2_ = value;
  // @@protoc_insertion_point(field_set:PLongIntIntByteByteStringValue.intValue2)
}

// sint32 byteValue1 = 4;
inline void PLongIntIntByteByteStringValue::clear_bytevalue1() {
  bytevalue1_ = 0;
}
inline ::google::protobuf::int32 PLongIntIntByteByteStringValue::bytevalue1() const {
  // @@protoc_insertion_point(field_get:PLongIntIntByteByteStringValue.byteValue1)
  return bytevalue1_;
}
inline void PLongIntIntByteByteStringValue::set_bytevalue1(::google::protobuf::int32 value) {
  
  bytevalue1_ = value;
  // @@protoc_insertion_point(field_set:PLongIntIntByteByteStringValue.byteValue1)
}

// sint32 byteValue2 = 5;
inline void PLongIntIntByteByteStringValue::clear_bytevalue2() {
  bytevalue2_ = 0;
}
inline ::google::protobuf::int32 PLongIntIntByteByteStringValue::bytevalue2() const {
  // @@protoc_insertion_point(field_get:PLongIntIntByteByteStringValue.byteValue2)
  return bytevalue2_;
}
inline void PLongIntIntByteByteStringValue::set_bytevalue2(::google::protobuf::int32 value) {
  
  bytevalue2_ = value;
  // @@protoc_insertion_point(field_set:PLongIntIntByteByteStringValue.byteValue2)
}

// .google.protobuf.StringValue stringValue = 6;
inline bool PLongIntIntByteByteStringValue::has_stringvalue() const {
  return this != internal_default_instance() && stringvalue_ != nullptr;
}
inline const ::google::protobuf::StringValue& PLongIntIntByteByteStringValue::stringvalue() const {
  const ::google::protobuf::StringValue* p = stringvalue_;
  // @@protoc_insertion_point(field_get:PLongIntIntByteByteStringValue.stringValue)
  return p != nullptr ? *p : *reinterpret_cast<const ::google::protobuf::StringValue*>(
      &::google::protobuf::_StringValue_default_instance_);
}
inline ::google::protobuf::StringValue* PLongIntIntByteByteStringValue::release_stringvalue() {
  // @@protoc_insertion_point(field_release:PLongIntIntByteByteStringValue.stringValue)
  
  ::google::protobuf::StringValue* temp = stringvalue_;
  stringvalue_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PLongIntIntByteByteStringValue::mutable_stringvalue() {
  
  if (stringvalue_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::StringValue>(GetArenaNoVirtual());
    stringvalue_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PLongIntIntByteByteStringValue.stringValue)
  return stringvalue_;
}
inline void PLongIntIntByteByteStringValue::set_allocated_stringvalue(::google::protobuf::StringValue* stringvalue) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(stringvalue_);
  }
  if (stringvalue) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(stringvalue)->GetArena();
    if (message_arena != submessage_arena) {
      stringvalue = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, stringvalue, submessage_arena);
    }
    
  } else {
    
  }
  stringvalue_ = stringvalue;
  // @@protoc_insertion_point(field_set_allocated:PLongIntIntByteByteStringValue.stringValue)
}

// -------------------------------------------------------------------

// PIntBooleanIntBooleanValue

// int32 intValue1 = 1;
inline void PIntBooleanIntBooleanValue::clear_intvalue1() {
  intvalue1_ = 0;
}
inline ::google::protobuf::int32 PIntBooleanIntBooleanValue::intvalue1() const {
  // @@protoc_insertion_point(field_get:PIntBooleanIntBooleanValue.intValue1)
  return intvalue1_;
}
inline void PIntBooleanIntBooleanValue::set_intvalue1(::google::protobuf::int32 value) {
  
  intvalue1_ = value;
  // @@protoc_insertion_point(field_set:PIntBooleanIntBooleanValue.intValue1)
}

// bool boolValue1 = 2;
inline void PIntBooleanIntBooleanValue::clear_boolvalue1() {
  boolvalue1_ = false;
}
inline bool PIntBooleanIntBooleanValue::boolvalue1() const {
  // @@protoc_insertion_point(field_get:PIntBooleanIntBooleanValue.boolValue1)
  return boolvalue1_;
}
inline void PIntBooleanIntBooleanValue::set_boolvalue1(bool value) {
  
  boolvalue1_ = value;
  // @@protoc_insertion_point(field_set:PIntBooleanIntBooleanValue.boolValue1)
}

// int32 intValue2 = 3;
inline void PIntBooleanIntBooleanValue::clear_intvalue2() {
  intvalue2_ = 0;
}
inline ::google::protobuf::int32 PIntBooleanIntBooleanValue::intvalue2() const {
  // @@protoc_insertion_point(field_get:PIntBooleanIntBooleanValue.intValue2)
  return intvalue2_;
}
inline void PIntBooleanIntBooleanValue::set_intvalue2(::google::protobuf::int32 value) {
  
  intvalue2_ = value;
  // @@protoc_insertion_point(field_set:PIntBooleanIntBooleanValue.intValue2)
}

// bool boolValue2 = 4;
inline void PIntBooleanIntBooleanValue::clear_boolvalue2() {
  boolvalue2_ = false;
}
inline bool PIntBooleanIntBooleanValue::boolvalue2() const {
  // @@protoc_insertion_point(field_get:PIntBooleanIntBooleanValue.boolValue2)
  return boolvalue2_;
}
inline void PIntBooleanIntBooleanValue::set_boolvalue2(bool value) {
  
  boolvalue2_ = value;
  // @@protoc_insertion_point(field_set:PIntBooleanIntBooleanValue.boolValue2)
}

// -------------------------------------------------------------------

// PStringStringValue

// .google.protobuf.StringValue stringValue1 = 1;
inline bool PStringStringValue::has_stringvalue1() const {
  return this != internal_default_instance() && stringvalue1_ != nullptr;
}
inline const ::google::protobuf::StringValue& PStringStringValue::stringvalue1() const {
  const ::google::protobuf::StringValue* p = stringvalue1_;
  // @@protoc_insertion_point(field_get:PStringStringValue.stringValue1)
  return p != nullptr ? *p : *reinterpret_cast<const ::google::protobuf::StringValue*>(
      &::google::protobuf::_StringValue_default_instance_);
}
inline ::google::protobuf::StringValue* PStringStringValue::release_stringvalue1() {
  // @@protoc_insertion_point(field_release:PStringStringValue.stringValue1)
  
  ::google::protobuf::StringValue* temp = stringvalue1_;
  stringvalue1_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PStringStringValue::mutable_stringvalue1() {
  
  if (stringvalue1_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::StringValue>(GetArenaNoVirtual());
    stringvalue1_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PStringStringValue.stringValue1)
  return stringvalue1_;
}
inline void PStringStringValue::set_allocated_stringvalue1(::google::protobuf::StringValue* stringvalue1) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(stringvalue1_);
  }
  if (stringvalue1) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(stringvalue1)->GetArena();
    if (message_arena != submessage_arena) {
      stringvalue1 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, stringvalue1, submessage_arena);
    }
    
  } else {
    
  }
  stringvalue1_ = stringvalue1;
  // @@protoc_insertion_point(field_set_allocated:PStringStringValue.stringValue1)
}

// .google.protobuf.StringValue stringValue2 = 2;
inline bool PStringStringValue::has_stringvalue2() const {
  return this != internal_default_instance() && stringvalue2_ != nullptr;
}
inline const ::google::protobuf::StringValue& PStringStringValue::stringvalue2() const {
  const ::google::protobuf::StringValue* p = stringvalue2_;
  // @@protoc_insertion_point(field_get:PStringStringValue.stringValue2)
  return p != nullptr ? *p : *reinterpret_cast<const ::google::protobuf::StringValue*>(
      &::google::protobuf::_StringValue_default_instance_);
}
inline ::google::protobuf::StringValue* PStringStringValue::release_stringvalue2() {
  // @@protoc_insertion_point(field_release:PStringStringValue.stringValue2)
  
  ::google::protobuf::StringValue* temp = stringvalue2_;
  stringvalue2_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PStringStringValue::mutable_stringvalue2() {
  
  if (stringvalue2_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::StringValue>(GetArenaNoVirtual());
    stringvalue2_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PStringStringValue.stringValue2)
  return stringvalue2_;
}
inline void PStringStringValue::set_allocated_stringvalue2(::google::protobuf::StringValue* stringvalue2) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(stringvalue2_);
  }
  if (stringvalue2) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(stringvalue2)->GetArena();
    if (message_arena != submessage_arena) {
      stringvalue2 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, stringvalue2, submessage_arena);
    }
    
  } else {
    
  }
  stringvalue2_ = stringvalue2;
  // @@protoc_insertion_point(field_set_allocated:PStringStringValue.stringValue2)
}

// -------------------------------------------------------------------

// PAnnotationValue

// string stringValue = 1;
inline bool PAnnotationValue::has_stringvalue() const {
  return field_case() == kStringValue;
}
inline void PAnnotationValue::set_has_stringvalue() {
  _oneof_case_[0] = kStringValue;
}
inline void PAnnotationValue::clear_stringvalue() {
  if (has_stringvalue()) {
    field_.stringvalue_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_field();
  }
}
inline const ::std::string& PAnnotationValue::stringvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.stringValue)
  if (has_stringvalue()) {
    return field_.stringvalue_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void PAnnotationValue::set_stringvalue(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:PAnnotationValue.stringValue)
  if (!has_stringvalue()) {
    clear_field();
    set_has_stringvalue();
    field_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  field_.stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PAnnotationValue.stringValue)
}
#if LANG_CXX11
inline void PAnnotationValue::set_stringvalue(::std::string&& value) {
  // @@protoc_insertion_point(field_set:PAnnotationValue.stringValue)
  if (!has_stringvalue()) {
    clear_field();
    set_has_stringvalue();
    field_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  field_.stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PAnnotationValue.stringValue)
}
#endif
inline void PAnnotationValue::set_stringvalue(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!has_stringvalue()) {
    clear_field();
    set_has_stringvalue();
    field_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  field_.stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PAnnotationValue.stringValue)
}
inline void PAnnotationValue::set_stringvalue(const char* value, size_t size) {
  if (!has_stringvalue()) {
    clear_field();
    set_has_stringvalue();
    field_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  field_.stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PAnnotationValue.stringValue)
}
inline ::std::string* PAnnotationValue::mutable_stringvalue() {
  if (!has_stringvalue()) {
    clear_field();
    set_has_stringvalue();
    field_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:PAnnotationValue.stringValue)
  return field_.stringvalue_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PAnnotationValue::release_stringvalue() {
  // @@protoc_insertion_point(field_release:PAnnotationValue.stringValue)
  if (has_stringvalue()) {
    clear_has_field();
    return field_.stringvalue_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return nullptr;
  }
}
inline void PAnnotationValue::set_allocated_stringvalue(::std::string* stringvalue) {
  if (has_field()) {
    clear_field();
  }
  if (stringvalue != nullptr) {
    set_has_stringvalue();
    field_.stringvalue_.UnsafeSetDefault(stringvalue);
  }
  // @@protoc_insertion_point(field_set_allocated:PAnnotationValue.stringValue)
}

// bool boolValue = 2;
inline bool PAnnotationValue::has_boolvalue() const {
  return field_case() == kBoolValue;
}
inline void PAnnotationValue::set_has_boolvalue() {
  _oneof_case_[0] = kBoolValue;
}
inline void PAnnotationValue::clear_boolvalue() {
  if (has_boolvalue()) {
    field_.boolvalue_ = false;
    clear_has_field();
  }
}
inline bool PAnnotationValue::boolvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.boolValue)
  if (has_boolvalue()) {
    return field_.boolvalue_;
  }
  return false;
}
inline void PAnnotationValue::set_boolvalue(bool value) {
  if (!has_boolvalue()) {
    clear_field();
    set_has_boolvalue();
  }
  field_.boolvalue_ = value;
  // @@protoc_insertion_point(field_set:PAnnotationValue.boolValue)
}

// int32 intValue = 3;
inline bool PAnnotationValue::has_intvalue() const {
  return field_case() == kIntValue;
}
inline void PAnnotationValue::set_has_intvalue() {
  _oneof_case_[0] = kIntValue;
}
inline void PAnnotationValue::clear_intvalue() {
  if (has_intvalue()) {
    field_.intvalue_ = 0;
    clear_has_field();
  }
}
inline ::google::protobuf::int32 PAnnotationValue::intvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.intValue)
  if (has_intvalue()) {
    return field_.intvalue_;
  }
  return 0;
}
inline void PAnnotationValue::set_intvalue(::google::protobuf::int32 value) {
  if (!has_intvalue()) {
    clear_field();
    set_has_intvalue();
  }
  field_.intvalue_ = value;
  // @@protoc_insertion_point(field_set:PAnnotationValue.intValue)
}

// int64 longValue = 4;
inline bool PAnnotationValue::has_longvalue() const {
  return field_case() == kLongValue;
}
inline void PAnnotationValue::set_has_longvalue() {
  _oneof_case_[0] = kLongValue;
}
inline void PAnnotationValue::clear_longvalue() {
  if (has_longvalue()) {
    field_.longvalue_ = PROTOBUF_LONGLONG(0);
    clear_has_field();
  }
}
inline ::google::protobuf::int64 PAnnotationValue::longvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.longValue)
  if (has_longvalue()) {
    return field_.longvalue_;
  }
  return PROTOBUF_LONGLONG(0);
}
inline void PAnnotationValue::set_longvalue(::google::protobuf::int64 value) {
  if (!has_longvalue()) {
    clear_field();
    set_has_longvalue();
  }
  field_.longvalue_ = value;
  // @@protoc_insertion_point(field_set:PAnnotationValue.longValue)
}

// sint32 shortValue = 5;
inline bool PAnnotationValue::has_shortvalue() const {
  return field_case() == kShortValue;
}
inline void PAnnotationValue::set_has_shortvalue() {
  _oneof_case_[0] = kShortValue;
}
inline void PAnnotationValue::clear_shortvalue() {
  if (has_shortvalue()) {
    field_.shortvalue_ = 0;
    clear_has_field();
  }
}
inline ::google::protobuf::int32 PAnnotationValue::shortvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.shortValue)
  if (has_shortvalue()) {
    return field_.shortvalue_;
  }
  return 0;
}
inline void PAnnotationValue::set_shortvalue(::google::protobuf::int32 value) {
  if (!has_shortvalue()) {
    clear_field();
    set_has_shortvalue();
  }
  field_.shortvalue_ = value;
  // @@protoc_insertion_point(field_set:PAnnotationValue.shortValue)
}

// double doubleValue = 6;
inline bool PAnnotationValue::has_doublevalue() const {
  return field_case() == kDoubleValue;
}
inline void PAnnotationValue::set_has_doublevalue() {
  _oneof_case_[0] = kDoubleValue;
}
inline void PAnnotationValue::clear_doublevalue() {
  if (has_doublevalue()) {
    field_.doublevalue_ = 0;
    clear_has_field();
  }
}
inline double PAnnotationValue::doublevalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.doubleValue)
  if (has_doublevalue()) {
    return field_.doublevalue_;
  }
  return 0;
}
inline void PAnnotationValue::set_doublevalue(double value) {
  if (!has_doublevalue()) {
    clear_field();
    set_has_doublevalue();
  }
  field_.doublevalue_ = value;
  // @@protoc_insertion_point(field_set:PAnnotationValue.doubleValue)
}

// bytes binaryValue = 7;
inline bool PAnnotationValue::has_binaryvalue() const {
  return field_case() == kBinaryValue;
}
inline void PAnnotationValue::set_has_binaryvalue() {
  _oneof_case_[0] = kBinaryValue;
}
inline void PAnnotationValue::clear_binaryvalue() {
  if (has_binaryvalue()) {
    field_.binaryvalue_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_field();
  }
}
inline const ::std::string& PAnnotationValue::binaryvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.binaryValue)
  if (has_binaryvalue()) {
    return field_.binaryvalue_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void PAnnotationValue::set_binaryvalue(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:PAnnotationValue.binaryValue)
  if (!has_binaryvalue()) {
    clear_field();
    set_has_binaryvalue();
    field_.binaryvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  field_.binaryvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PAnnotationValue.binaryValue)
}
#if LANG_CXX11
inline void PAnnotationValue::set_binaryvalue(::std::string&& value) {
  // @@protoc_insertion_point(field_set:PAnnotationValue.binaryValue)
  if (!has_binaryvalue()) {
    clear_field();
    set_has_binaryvalue();
    field_.binaryvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  field_.binaryvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PAnnotationValue.binaryValue)
}
#endif
inline void PAnnotationValue::set_binaryvalue(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!has_binaryvalue()) {
    clear_field();
    set_has_binaryvalue();
    field_.binaryvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  field_.binaryvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PAnnotationValue.binaryValue)
}
inline void PAnnotationValue::set_binaryvalue(const void* value, size_t size) {
  if (!has_binaryvalue()) {
    clear_field();
    set_has_binaryvalue();
    field_.binaryvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  field_.binaryvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PAnnotationValue.binaryValue)
}
inline ::std::string* PAnnotationValue::mutable_binaryvalue() {
  if (!has_binaryvalue()) {
    clear_field();
    set_has_binaryvalue();
    field_.binaryvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:PAnnotationValue.binaryValue)
  return field_.binaryvalue_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PAnnotationValue::release_binaryvalue() {
  // @@protoc_insertion_point(field_release:PAnnotationValue.binaryValue)
  if (has_binaryvalue()) {
    clear_has_field();
    return field_.binaryvalue_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return nullptr;
  }
}
inline void PAnnotationValue::set_allocated_binaryvalue(::std::string* binaryvalue) {
  if (has_field()) {
    clear_field();
  }
  if (binaryvalue != nullptr) {
    set_has_binaryvalue();
    field_.binaryvalue_.UnsafeSetDefault(binaryvalue);
  }
  // @@protoc_insertion_point(field_set_allocated:PAnnotationValue.binaryValue)
}

// sint32 byteValue = 8;
inline bool PAnnotationValue::has_bytevalue() const {
  return field_case() == kByteValue;
}
inline void PAnnotationValue::set_has_bytevalue() {
  _oneof_case_[0] = kByteValue;
}
inline void PAnnotationValue::clear_bytevalue() {
  if (has_bytevalue()) {
    field_.bytevalue_ = 0;
    clear_has_field();
  }
}
inline ::google::protobuf::int32 PAnnotationValue::bytevalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.byteValue)
  if (has_bytevalue()) {
    return field_.bytevalue_;
  }
  return 0;
}
inline void PAnnotationValue::set_bytevalue(::google::protobuf::int32 value) {
  if (!has_bytevalue()) {
    clear_field();
    set_has_bytevalue();
  }
  field_.bytevalue_ = value;
  // @@protoc_insertion_point(field_set:PAnnotationValue.byteValue)
}

// .PIntStringValue intStringValue = 9;
inline bool PAnnotationValue::has_intstringvalue() const {
  return field_case() == kIntStringValue;
}
inline void PAnnotationValue::set_has_intstringvalue() {
  _oneof_case_[0] = kIntStringValue;
}
inline void PAnnotationValue::clear_intstringvalue() {
  if (has_intstringvalue()) {
    delete field_.intstringvalue_;
    clear_has_field();
  }
}
inline ::PIntStringValue* PAnnotationValue::release_intstringvalue() {
  // @@protoc_insertion_point(field_release:PAnnotationValue.intStringValue)
  if (has_intstringvalue()) {
    clear_has_field();
      ::PIntStringValue* temp = field_.intstringvalue_;
    field_.intstringvalue_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PIntStringValue& PAnnotationValue::intstringvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.intStringValue)
  return has_intstringvalue()
      ? *field_.intstringvalue_
      : *reinterpret_cast< ::PIntStringValue*>(&::_PIntStringValue_default_instance_);
}
inline ::PIntStringValue* PAnnotationValue::mutable_intstringvalue() {
  if (!has_intstringvalue()) {
    clear_field();
    set_has_intstringvalue();
    field_.intstringvalue_ = CreateMaybeMessage< ::PIntStringValue >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:PAnnotationValue.intStringValue)
  return field_.intstringvalue_;
}

// .PStringStringValue stringStringValue = 10;
inline bool PAnnotationValue::has_stringstringvalue() const {
  return field_case() == kStringStringValue;
}
inline void PAnnotationValue::set_has_stringstringvalue() {
  _oneof_case_[0] = kStringStringValue;
}
inline void PAnnotationValue::clear_stringstringvalue() {
  if (has_stringstringvalue()) {
    delete field_.stringstringvalue_;
    clear_has_field();
  }
}
inline ::PStringStringValue* PAnnotationValue::release_stringstringvalue() {
  // @@protoc_insertion_point(field_release:PAnnotationValue.stringStringValue)
  if (has_stringstringvalue()) {
    clear_has_field();
      ::PStringStringValue* temp = field_.stringstringvalue_;
    field_.stringstringvalue_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PStringStringValue& PAnnotationValue::stringstringvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.stringStringValue)
  return has_stringstringvalue()
      ? *field_.stringstringvalue_
      : *reinterpret_cast< ::PStringStringValue*>(&::_PStringStringValue_default_instance_);
}
inline ::PStringStringValue* PAnnotationValue::mutable_stringstringvalue() {
  if (!has_stringstringvalue()) {
    clear_field();
    set_has_stringstringvalue();
    field_.stringstringvalue_ = CreateMaybeMessage< ::PStringStringValue >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:PAnnotationValue.stringStringValue)
  return field_.stringstringvalue_;
}

// .PIntStringStringValue intStringStringValue = 11;
inline bool PAnnotationValue::has_intstringstringvalue() const {
  return field_case() == kIntStringStringValue;
}
inline void PAnnotationValue::set_has_intstringstringvalue() {
  _oneof_case_[0] = kIntStringStringValue;
}
inline void PAnnotationValue::clear_intstringstringvalue() {
  if (has_intstringstringvalue()) {
    delete field_.intstringstringvalue_;
    clear_has_field();
  }
}
inline ::PIntStringStringValue* PAnnotationValue::release_intstringstringvalue() {
  // @@protoc_insertion_point(field_release:PAnnotationValue.intStringStringValue)
  if (has_intstringstringvalue()) {
    clear_has_field();
      ::PIntStringStringValue* temp = field_.intstringstringvalue_;
    field_.intstringstringvalue_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PIntStringStringValue& PAnnotationValue::intstringstringvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.intStringStringValue)
  return has_intstringstringvalue()
      ? *field_.intstringstringvalue_
      : *reinterpret_cast< ::PIntStringStringValue*>(&::_PIntStringStringValue_default_instance_);
}
inline ::PIntStringStringValue* PAnnotationValue::mutable_intstringstringvalue() {
  if (!has_intstringstringvalue()) {
    clear_field();
    set_has_intstringstringvalue();
    field_.intstringstringvalue_ = CreateMaybeMessage< ::PIntStringStringValue >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:PAnnotationValue.intStringStringValue)
  return field_.intstringstringvalue_;
}

// .PLongIntIntByteByteStringValue longIntIntByteByteStringValue = 12;
inline bool PAnnotationValue::has_longintintbytebytestringvalue() const {
  return field_case() == kLongIntIntByteByteStringValue;
}
inline void PAnnotationValue::set_has_longintintbytebytestringvalue() {
  _oneof_case_[0] = kLongIntIntByteByteStringValue;
}
inline void PAnnotationValue::clear_longintintbytebytestringvalue() {
  if (has_longintintbytebytestringvalue()) {
    delete field_.longintintbytebytestringvalue_;
    clear_has_field();
  }
}
inline ::PLongIntIntByteByteStringValue* PAnnotationValue::release_longintintbytebytestringvalue() {
  // @@protoc_insertion_point(field_release:PAnnotationValue.longIntIntByteByteStringValue)
  if (has_longintintbytebytestringvalue()) {
    clear_has_field();
      ::PLongIntIntByteByteStringValue* temp = field_.longintintbytebytestringvalue_;
    field_.longintintbytebytestringvalue_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PLongIntIntByteByteStringValue& PAnnotationValue::longintintbytebytestringvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.longIntIntByteByteStringValue)
  return has_longintintbytebytestringvalue()
      ? *field_.longintintbytebytestringvalue_
      : *reinterpret_cast< ::PLongIntIntByteByteStringValue*>(&::_PLongIntIntByteByteStringValue_default_instance_);
}
inline ::PLongIntIntByteByteStringValue* PAnnotationValue::mutable_longintintbytebytestringvalue() {
  if (!has_longintintbytebytestringvalue()) {
    clear_field();
    set_has_longintintbytebytestringvalue();
    field_.longintintbytebytestringvalue_ = CreateMaybeMessage< ::PLongIntIntByteByteStringValue >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:PAnnotationValue.longIntIntByteByteStringValue)
  return field_.longintintbytebytestringvalue_;
}

// .PIntBooleanIntBooleanValue intBooleanIntBooleanValue = 13;
inline bool PAnnotationValue::has_intbooleanintbooleanvalue() const {
  return field_case() == kIntBooleanIntBooleanValue;
}
inline void PAnnotationValue::set_has_intbooleanintbooleanvalue() {
  _oneof_case_[0] = kIntBooleanIntBooleanValue;
}
inline void PAnnotationValue::clear_intbooleanintbooleanvalue() {
  if (has_intbooleanintbooleanvalue()) {
    delete field_.intbooleanintbooleanvalue_;
    clear_has_field();
  }
}
inline ::PIntBooleanIntBooleanValue* PAnnotationValue::release_intbooleanintbooleanvalue() {
  // @@protoc_insertion_point(field_release:PAnnotationValue.intBooleanIntBooleanValue)
  if (has_intbooleanintbooleanvalue()) {
    clear_has_field();
      ::PIntBooleanIntBooleanValue* temp = field_.intbooleanintbooleanvalue_;
    field_.intbooleanintbooleanvalue_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PIntBooleanIntBooleanValue& PAnnotationValue::intbooleanintbooleanvalue() const {
  // @@protoc_insertion_point(field_get:PAnnotationValue.intBooleanIntBooleanValue)
  return has_intbooleanintbooleanvalue()
      ? *field_.intbooleanintbooleanvalue_
      : *reinterpret_cast< ::PIntBooleanIntBooleanValue*>(&::_PIntBooleanIntBooleanValue_default_instance_);
}
inline ::PIntBooleanIntBooleanValue* PAnnotationValue::mutable_intbooleanintbooleanvalue() {
  if (!has_intbooleanintbooleanvalue()) {
    clear_field();
    set_has_intbooleanintbooleanvalue();
    field_.intbooleanintbooleanvalue_ = CreateMaybeMessage< ::PIntBooleanIntBooleanValue >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:PAnnotationValue.intBooleanIntBooleanValue)
  return field_.intbooleanintbooleanvalue_;
}

inline bool PAnnotationValue::has_field() const {
  return field_case() != FIELD_NOT_SET;
}
inline void PAnnotationValue::clear_has_field() {
  _oneof_case_[0] = FIELD_NOT_SET;
}
inline PAnnotationValue::FieldCase PAnnotationValue::field_case() const {
  return PAnnotationValue::FieldCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// PAnnotation

// int32 key = 1;
inline void PAnnotation::clear_key() {
  key_ = 0;
}
inline ::google::protobuf::int32 PAnnotation::key() const {
  // @@protoc_insertion_point(field_get:PAnnotation.key)
  return key_;
}
inline void PAnnotation::set_key(::google::protobuf::int32 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:PAnnotation.key)
}

// .PAnnotationValue value = 2;
inline bool PAnnotation::has_value() const {
  return this != internal_default_instance() && value_ != nullptr;
}
inline void PAnnotation::clear_value() {
  if (GetArenaNoVirtual() == nullptr && value_ != nullptr) {
    delete value_;
  }
  value_ = nullptr;
}
inline const ::PAnnotationValue& PAnnotation::value() const {
  const ::PAnnotationValue* p = value_;
  // @@protoc_insertion_point(field_get:PAnnotation.value)
  return p != nullptr ? *p : *reinterpret_cast<const ::PAnnotationValue*>(
      &::_PAnnotationValue_default_instance_);
}
inline ::PAnnotationValue* PAnnotation::release_value() {
  // @@protoc_insertion_point(field_release:PAnnotation.value)
  
  ::PAnnotationValue* temp = value_;
  value_ = nullptr;
  return temp;
}
inline ::PAnnotationValue* PAnnotation::mutable_value() {
  
  if (value_ == nullptr) {
    auto* p = CreateMaybeMessage<::PAnnotationValue>(GetArenaNoVirtual());
    value_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PAnnotation.value)
  return value_;
}
inline void PAnnotation::set_allocated_value(::PAnnotationValue* value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete value_;
  }
  if (value) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, value, submessage_arena);
    }
    
  } else {
    
  }
  value_ = value;
  // @@protoc_insertion_point(field_set_allocated:PAnnotation.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Annotation_2eproto
